version: "3.1"

services:
  deepdetect:
    image: jolibrain/deepdetect_cpu
    container_name: deepdetect
    ports:
      - "8008:8080"
  thinker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - deepdetect
    container_name: thinker
    ports:
      - "8009:8080"