version: "3.1"

services:
  deepdetect:
    network_mode: host
    image: jolibrain/deepdetect_cpu
    container_name: deepdetect
    ports:
      - "8008:8080"
  thinker:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - deepdetect
    container_name: thinker
    ports:
      - "8009:8081"